In [1]:
import pandas as pd

In [2]:
data = pd.read_csv(r'D:/kuliyaah/semester 5/data sains/food_delivery_datasets.csv')
print(data)

        order_id  voucher_amount                   date_time  eta_seconds  \
0     FOOD-10455               0  2018-08-12T20:35:08.001006         1800
1     FOOD-10985               0  2018-09-23T17:44:12.243273         2173
2     FOOD-10911               0  2018-09-19T18:08:09.387991         1418
3     FOOD-10932               0  2018-09-21T01:24:35.272499         1903
4     FOOD-10961               0  2018-09-22T17:57:45.523161         1716
...          ...             ...                         ...          ...
1071  FOOD-10921               0  2018-09-20T15:01:52.152828          900
1072  FOOD-10265            5000  2018-07-26T14:43:23.655294         1579
1073  FOOD-10534               0  2018-08-21T20:10:59.283185         2606
1074  FOOD-10158               0  2018-07-16T14:42:23.214427         2428
1075  FOOD-10770               0  2018-09-11T14:18:19.494258         1547

      food_price  cust_id  rating  delivery_fee   resto_id     status  \
0          18900  1089034     5.0          4000  742638033  Completed
1         149000   180146     5.0         11000  742767245  Completed
2          43800   366528     NaN          9000  742618303  Completed
3          39900   511038     5.0         14000  742541172  Completed
4          77700  1220358     NaN          4000  742604875  Completed
...          ...      ...     ...           ...        ...        ...
1071      103200  1296335     5.0          4000  742742150  Completed
1072      145700  1135466     5.0          7000  742566851  Completed
1073      177200  1383625     NaN         15000  742571888  Completed
1074       49300  1094787     5.0          9000  742725064  Completed
1075       43000  1010922     5.0          9000  742594499  Completed

      random_id
0      0.511149
1      0.832936
2      0.828026
3      0.239377
4      0.995587
...         ...
1071   0.248328
1072   0.268251
1073   0.132528
1074   0.167946
1075   0.358051

[1076 rows x 11 columns]

In [3]:
#delivery fee termurah
delivery_fee=data.groupby("delivery_fee").min()

In [4]:
delivery_fee

,order_id,voucher_amount,date_time,eta_seconds,food_price,cust_id,rating,resto_id,status,random_id
delivery_fee,,,,,,,,,,
0,FOOD-10012,0,2018-07-02T12:26:59.856025,3,18400,82690,3.0,200000639,Cancelled,0.010569
1000,FOOD-10083,0,2018-07-08T18:45:36.398656,350,21100,158214,5.0,742537924,Cancelled,0.067518
2000,FOOD-10002,0,2018-07-01T12:05:29.702194,7,15700,82690,4.0,742528179,Cancelled,0.011022
3000,FOOD-10223,0,2018-07-22T13:10:45.480457,239,28500,366721,5.0,200005639,Cancelled,0.022089
4000,FOOD-10018,0,2018-07-02T20:37:07.569905,3,14200,62551,1.0,742526134,Cancelled,0.015554
5000,FOOD-10001,0,2018-07-01T11:36:10.581264,5,18700,180146,5.0,200003382,Cancelled,0.037066
6000,FOOD-10019,0,2018-07-03T12:12:51.406644,663,18400,103236,5.0,200003475,Cancelled,0.040218
7000,FOOD-10007,0,2018-07-01T17:26:25.337694,3,19000,316834,5.0,742528002,Cancelled,0.025599
8000,FOOD-10032,0,2018-07-04T13:05:10.988492,2,21900,70701,5.0,200005639,Cancelled,0.100112
9000,FOOD-10011,0,2018-07-01T23:47:20.206826,3,12900,22895,3.0,200001973,Cancelled,0.001616
10000,FOOD-10004,0,2018-07-01T14:24:06.719768,3,19100,70701,3.0,200001006,Cancelled,0.005980
11000,FOOD-10033,0,2018-07-04T14:20:23.995534,4,28300,103236,4.0,742526555,Cancelled,0.015804
12000,FOOD-10003,0,2018-07-01T13:40:19.932690,2,25200,59565,5.0,200000964,Cancelled,0.019027
13000,FOOD-10005,0,2018-07-01T16:31:35.700543,59,24900,59565,4.0,742525319,Cancelled,0.013510
14000,FOOD-10025,0,2018-07-03T17:26:54.054508,9,28600,193679,4.0,742526789,Cancelled,0.010422
15000,FOOD-10029,0,2018-07-03T21:37:15.644905,5,20300,103236,5.0,742534370,Cancelled,0.013770
16000,FOOD-10056,0,2018-07-06T15:12:14.328757,2,27200,103236,5.0,200009033,Cancelled,0.025207
17000,FOOD-10139,0,2018-07-14T17:24:02.794245,20,87400,161917,4.0,742539744,Cancelled,0.045840
18000,FOOD-10078,0,2018-07-08T16:02:38.629791,121,22100,103236,5.0,200009033,Cancelled,0.232213
19000,FOOD-10119,0,2018-07-12T11:18:13.950877,10,38800,304856,5.0,742527930,Cancelled,0.176650
20000,FOOD-10565,0,2018-08-24T12:13:00.042608,10,34100,304856,4.0,742526724,Cancelled,0.077888
21000,FOOD-10022,0,2018-07-03T13:59:02.357292,123,37400,304856,4.0,742524646,Cancelled,0.106381
22000,FOOD-10044,0,2018-07-05T14:47:14.035205,4,36200,128682,5.0,200011181,Cancelled,0.115263
23000,FOOD-10293,0,2018-07-29T10:32:11.187058,2528,37600,366528,5.0,742582839,Completed,0.086766
24000,FOOD-10508,0,2018-08-18T21:00:40.422084,5,76000,123830,5.0,742527930,Cancelled,0.026208
25000,FOOD-10134,0,2018-07-14T15:19:59.320384,219,55100,410472,5.0,742539582,Cancelled,0.093822
28000,FOOD-10346,0,2018-08-03T17:40:30.222874,94,63300,128682,5.0,742528562,Cancelled,0.244379
29000,FOOD-10854,0,2018-09-16T14:01:56.620406,63,88500,361927,NaN,742622470,Cancelled,0.036496
30000,FOOD-10839,0,2018-09-15T20:00:42.817206,66,90900,355305,5.0,200001979,Cancelled,0.040307
32000,FOOD-10856,0,2018-09-16T14:06:19.267336,320,88900,361927,NaN,742622470,Cancelled,0.928857
33000,FOOD-10850,0,2018-09-16T13:50:02.085816,148,89400,361927,NaN,742622470,Cancelled,0.247009
34000,FOOD-10483,0,2018-08-16T16:58:41.524429,1587,63800,366528,NaN,742582839,Cancelled,0.333369
35000,FOOD-10484,0,2018-08-16T17:00:02.563219,88,63000,366528,NaN,742582839,Cancelled,0.203204
36000,FOOD-10844,0,2018-09-16T11:00:55.539184,171,89200,361927,NaN,742526665,Cancelled,0.241890
37000,FOOD-10982,0,2018-09-23T15:53:13.903397,2340,300300,366721,5.0,742628548,Completed,0.163592
38000,FOOD-10848,0,2018-09-16T13:44:04.620649,122,89200,361927,NaN,742792299,Cancelled,0.223004
39000,FOOD-10380,0,2018-08-05T22:08:25.424821,375,142700,1383625,NaN,200003382,Cancelled,0.837287
40000,FOOD-10460,0,2018-08-13T14:48:23.789972,5527,103100,1191779,NaN,742541893,Completed,0.587890
43000,FOOD-10381,0,2018-08-05T22:15:05.095392,45,142100,1294885,NaN,200003382,Cancelled,0.304505
44000,FOOD-10382,0,2018-08-05T22:18:54.638622,2887,141400,1383625,NaN,200003382,Completed,0.138681